import { Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../../api/client";
import type { MusicCharacterResponse, MusicCharacterRewrite, MusicSource, Prerequisites } from "../../types/api";
import { GlowPanel } from "../GlowPanel";

type CharacterPeriod = "this_month" | "month" | "rolling_year";
export function MusicCharacterSection({ prerequisites, source }: { prerequisites: Prerequisites | null; source: MusicSource }) {
  const [period] = useState<CharacterPeriod>("rolling_year"); const [selectedMonth, setSelectedMonth] = useState<string | null>(null);
  const [character, setCharacter] = useState<MusicCharacterResponse | null>(null); const [rewrite, setRewrite] = useState<MusicCharacterRewrite | null>(null);
  const [loading, setLoading] = useState(false); const [rewriting, setRewriting] = useState(false); const [rewriteError, setRewriteError] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; setLoading(true); setRewrite(null); api.musicCharacter(period, period === "month" ? selectedMonth : null, source).then((next) => { if (!cancelled) { setCharacter(next); if (!selectedMonth && next.period.available_months.length) setSelectedMonth(next.period.available_months.at(-1)?.value ?? null); } }).catch(() => { if (!cancelled) setCharacter(null); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [period, selectedMonth, source]);
  if (!character) return <GlowPanel as="section" variant="card" className="p-6"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-red-200">Your Music Character</p><p className="mt-3 text-mist">{loading ? "Reading your music character..." : "Music Character will appear after a refresh with listening data."}</p></GlowPanel>;
  const canRewrite = Boolean(prerequisites?.ollama_reachable && prerequisites.model_installed); const primary = character.primary;
  const personalise = async () => { if (!canRewrite) return; setRewriting(true); setRewriteError(null); try { setRewrite(await api.rewriteMusicCharacter(period, period === "month" ? selectedMonth : null, "playful", source)); } catch (error) { setRewriteError(error instanceof Error ? error.message : "Personalised rewrite unavailable."); } finally { setRewriting(false); } };
  return <GlowPanel as="section" variant="major" className="overflow-hidden"><div className="grid gap-0 xl:grid-cols-[1.05fr_0.95fr]"><div className="relative border-b border-white/10 p-5 lg:p-6 xl:border-b-0 xl:border-r xl:border-white/10"><div className="relative"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-red-200">Your Music Character</p><h2 className="mt-3 text-3xl font-black leading-tight text-white md:text-4xl">{rewrite?.headline || primary.name}</h2><div className="mt-4 flex flex-wrap gap-2"><Badge label={character.period.label} /><Badge label="Deterministic read" /><Badge label={canRewrite ? "Gemma rewrite ready" : "Gemma rewrite offline"} /></div><div className="mt-5 flex flex-wrap gap-2"><button className="btn-primary" onClick={personalise} disabled={!canRewrite || rewriting}><Sparkles size={17} />{rewriting ? "Rewriting..." : "Make it more personal"}</button>{rewriteError && <p className="text-sm text-amber-100">{rewriteError}</p>}</div><GlowPanel as="p" variant="row" wrapperClassName="mt-6" className="p-4 text-xl font-black leading-snug text-red-50">{rewrite?.friendly_roast || rewrite?.one_liner || primary.roast}</GlowPanel><p className="mt-5 max-w-3xl text-base leading-8 text-mist">{rewrite?.profile_paragraph || primary.profile}</p><div className="mt-6 flex flex-wrap gap-2">{character.habits.map((habit) => <span key={habit} className="rounded-full border border-white/10 bg-black/25 px-3 py-1.5 text-sm text-mist">{habit}</span>)}</div></div></div><div className="p-5 lg:p-6"><div className="grid gap-4 sm:grid-cols-2"><Mini title="Secondary character" value={character.secondary?.name ?? "No strong secondary yet"} body={character.secondary?.profile ?? "The primary character carries most of the signal for this period."} /><Mini title="Listening habits" value={character.habits.join(" / ") || "No strong habit yet"} body="Habits describe how you listen; personality describes what your taste sounds and feels like." /></div></div></div></GlowPanel>;
}
function Badge({ label }: { label: string }) { return <span className="rounded-full border border-red-400/25 bg-red-500/10 px-3 py-1.5 text-xs font-semibold text-red-100">{label}</span>; }
function Mini({ title, value, body }: { title: string; value: string; body: string }) { return <GlowPanel as="div" variant="row" className="p-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-mist/60">{title}</p><p className="mt-3 text-lg font-black leading-6 text-white">{value}</p><p className="mt-3 text-sm leading-6 text-mist">{body}</p></GlowPanel>; }
